# Generated by Django 6.0.2 on 2026-02-23 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='닉네임')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=20, verbose_name='핸드폰번호')),
                ('grade', models.IntegerField(default=1, verbose_name='회원등급 ex)1=일반회원, 2=스태프, 3=관리자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('DELETING', '삭제 대기'), ('DELETED', '삭제 완료')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grade'], name='users_grade_871f3e_idx'), models.Index(fields=['status'], name='users_status_9ca66f_idx')],
            },
        ),
    ]
