# Generated by Django 6.0.2 on 2026-02-24 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["-created_at"], "verbose_name": "유저", "verbose_name_plural": "유저 목록"},
        ),
    ]
