# Generated by Django 6.0.2 on 2026-02-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accounts", to=settings.AUTH_USER_MODEL, verbose_name="소유자"),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("user", "bank_code", "account_number")},
        ),
    ]
