# Generated by Django 6.0.2 on 2026-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.BigIntegerField(default=0, verbose_name="잔액"),
        ),
    ]
