# Generated by Django 6.0.2 on 2026-02-24 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="거래금액")),
                ("balance_after", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="거래후잔액")),
                ("description", models.CharField(max_length=255, verbose_name="거래내역")),
                ("transaction_type", models.CharField(choices=[("INCOME", "수입"), ("EXPENSE", "지출")], max_length=20, verbose_name="거래유형")),
                ("transaction_method", models.CharField(max_length=20, verbose_name="결제수단")),
                ("transaction_at", models.DateTimeField(auto_now_add=True, verbose_name="거래일시")),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="accounts.account", verbose_name="계좌ID")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to=settings.AUTH_USER_MODEL, verbose_name="작성자")),
            ],
            options={
                "verbose_name": "거래내역",
                "verbose_name_plural": "거래내역 목록",
                "db_table": "transaction_history",
            },
        ),
    ]
