# Generated by Django 6.0.2 on 2026-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.BigIntegerField(default=0, verbose_name="거래금액"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_after",
            field=models.BigIntegerField(default=0, verbose_name="거래후잔액"),
        ),
    ]
