# Generated by Django 6.0.2 on 2026-02-25 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(max_length=50, verbose_name="분석 대상(수입/지출)")),
                ("period_type", models.CharField(max_length=20, verbose_name="분석 기간 단위")),
                ("start_date", models.DateField(verbose_name="분석 시작일")),
                ("end_date", models.DateField(verbose_name="분석 종료일")),
                ("description", models.TextField(verbose_name="분석 결과 설명")),
                ("result_image", models.ImageField(blank=True, null=True, upload_to="analysis/charts/%Y/%m/", verbose_name="분석 결과 이미지")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 시간")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시간")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analyses", to=settings.AUTH_USER_MODEL, verbose_name="분석 대상 유저")),
            ],
            options={
                "verbose_name": "분석 데이터",
                "verbose_name_plural": "분석 데이터 목록",
                "db_table": "analysis",
            },
        ),
    ]
