# Generated by Django 6.0.2 on 2026-02-25 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="period_type",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="target_type",
        ),
    ]
