# Generated by Django 6.0.2 on 2026-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_remove_analysis_period_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="period_type",
            field=models.CharField(default="weekly", max_length=20, verbose_name="분석 기간 단위"),
            preserve_default=False,
        ),
    ]
